package discovery

// Error is an error generated by the discovery service
type Error string

func (e Error) Error() string {
	return string(e)
}

// BypassDiscovery should return true if the address is not discoverable
// by the discovery service, and the address should use net.Dailer directly instead
//
// This error behavior is used to filter address which should be using discovery from those
// which should be dialed without any discovery
func (e Error) BypassDiscovery() bool {
	return e == ErrUndiscoverable
}

// ErrUndiscoverable indicates a Discoverer cannot use the provided address for discovery
const ErrUndiscoverable = Error("discovery: undiscoverable address")
